"""Check relationship changes

Revision ID: 9b66be447756
Revises: b280e1b5ec16
Create Date: 2026-07-17 22:05:39.282555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b66be447756'
down_revision: Union[str, None] = 'b280e1b5ec16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_answers_updated_by_users'), 'answers', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_answers_created_by_users'), 'answers', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_assessment_sessions_created_by_users'), 'assessment_sessions', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_assessment_sessions_updated_by_users'), 'assessment_sessions', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_audit_logs_created_by_users'), 'audit_logs', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_audit_logs_updated_by_users'), 'audit_logs', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_categories_created_by_users'), 'categories', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_categories_updated_by_users'), 'categories', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_category_question_mappings_created_by_users'), 'category_question_mappings', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_category_question_mappings_updated_by_users'), 'category_question_mappings', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_event_outbox_created_by_users'), 'event_outbox', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_event_outbox_updated_by_users'), 'event_outbox', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_permissions_updated_by_users'), 'permissions', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_permissions_created_by_users'), 'permissions', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_questions_created_by_users'), 'questions', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_questions_updated_by_users'), 'questions', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_registration_counters_created_by_users'), 'registration_counters', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_registration_counters_updated_by_users'), 'registration_counters', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_role_permissions_updated_by_users'), 'role_permissions', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_role_permissions_created_by_users'), 'role_permissions', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_roles_updated_by_users'), 'roles', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_roles_created_by_users'), 'roles', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_system_settings_created_by_users'), 'system_settings', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_system_settings_updated_by_users'), 'system_settings', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_user_profiles_updated_by_users'), 'user_profiles', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_user_profiles_created_by_users'), 'user_profiles', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_user_responses_created_by_users'), 'user_responses', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_user_responses_updated_by_users'), 'user_responses', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_users_updated_by_users'), 'users', 'users', ['updated_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_users_created_by_users'), 'users', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_created_by_users'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_updated_by_users'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_responses_updated_by_users'), 'user_responses', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_responses_created_by_users'), 'user_responses', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_profiles_created_by_users'), 'user_profiles', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_profiles_updated_by_users'), 'user_profiles', type_='foreignkey')
    op.drop_constraint(op.f('fk_system_settings_updated_by_users'), 'system_settings', type_='foreignkey')
    op.drop_constraint(op.f('fk_system_settings_created_by_users'), 'system_settings', type_='foreignkey')
    op.drop_constraint(op.f('fk_roles_created_by_users'), 'roles', type_='foreignkey')
    op.drop_constraint(op.f('fk_roles_updated_by_users'), 'roles', type_='foreignkey')
    op.drop_constraint(op.f('fk_role_permissions_created_by_users'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('fk_role_permissions_updated_by_users'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('fk_registration_counters_updated_by_users'), 'registration_counters', type_='foreignkey')
    op.drop_constraint(op.f('fk_registration_counters_created_by_users'), 'registration_counters', type_='foreignkey')
    op.drop_constraint(op.f('fk_questions_updated_by_users'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('fk_questions_created_by_users'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('fk_permissions_created_by_users'), 'permissions', type_='foreignkey')
    op.drop_constraint(op.f('fk_permissions_updated_by_users'), 'permissions', type_='foreignkey')
    op.drop_constraint(op.f('fk_event_outbox_updated_by_users'), 'event_outbox', type_='foreignkey')
    op.drop_constraint(op.f('fk_event_outbox_created_by_users'), 'event_outbox', type_='foreignkey')
    op.drop_constraint(op.f('fk_category_question_mappings_updated_by_users'), 'category_question_mappings', type_='foreignkey')
    op.drop_constraint(op.f('fk_category_question_mappings_created_by_users'), 'category_question_mappings', type_='foreignkey')
    op.drop_constraint(op.f('fk_categories_updated_by_users'), 'categories', type_='foreignkey')
    op.drop_constraint(op.f('fk_categories_created_by_users'), 'categories', type_='foreignkey')
    op.drop_constraint(op.f('fk_audit_logs_updated_by_users'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('fk_audit_logs_created_by_users'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('fk_assessment_sessions_updated_by_users'), 'assessment_sessions', type_='foreignkey')
    op.drop_constraint(op.f('fk_assessment_sessions_created_by_users'), 'assessment_sessions', type_='foreignkey')
    op.drop_constraint(op.f('fk_answers_created_by_users'), 'answers', type_='foreignkey')
    op.drop_constraint(op.f('fk_answers_updated_by_users'), 'answers', type_='foreignkey')
    # ### end Alembic commands ###
